-- 코드를 입력하세요
SELECT BOOK.AUTHOR_ID,AUTHOR.AUTHOR_NAME,BOOK.CATEGORY,SUM(BOOK_SALES.SALES*BOOK.PRICE) AS TOTAL_SALES
FROM BOOK_SALES
LEFT JOIN BOOK ON BOOK.BOOK_ID=BOOK_SALES.BOOK_ID
LEFT JOIN AUTHOR ON AUTHOR.AUTHOR_ID=BOOK.AUTHOR_ID
WHERE YEAR(BOOK_SALES.SALES_DATE) = 2022 AND MONTH(BOOK_SALES.SALES_DATE) = 1
GROUP BY BOOK.AUTHOR_ID,BOOK.CATEGORY
ORDER BY BOOK.AUTHOR_ID ASC, BOOK.CATEGORY DESC;

# SELECT BOOK.AUTHOR_ID,AUTHOR.AUTHOR_NAME,BOOK.CATEGORY,SUM(BOOK_SALES.SALES)
# FROM BOOK_SALES
# INNER JOIN BOOK ON BOOK.BOOK_ID=BOOK_SALES.BOOK_ID
# LEFT JOIN AUTHOR ON AUTHOR.AUTHOR_ID=BOOK.AUTHOR_ID
# WHERE BOOK_SALES.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
# GROUP BY BOOK.AUTHOR_ID,BOOK.CATEGORY;

