-- 코드를 입력하세요 

# SELECT CAR.CAR_ID,CAR.CAR_TYPE, TRUNCATE ((CAR.DAILY_FEE*((100-PLAN.DISCOUNT_RATE)/100))*30,0) FEE
# FROM CAR_RENTAL_COMPANY_CAR CAR
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN 
# ON CAR.CAR_TYPE=PLAN.CAR_TYPE 
# AND CAR.CAR_TYPE IN ('세단','suv') 
# AND PLAN.DURATION_TYPE LIKE '30일 이상'
# WHERE TRUNCATE ((CAR.DAILY_FEE*((100-PLAN.DISCOUNT_RATE)/100))*30,0) BETWEEN 500000 AND 2000000
# AND CAR.CAR_ID NOT IN (SELECT DISTINCT(HISTORY.CAR_ID) 
#                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
#                        WHERE HISTORY.START_DATE BETWEEN '2022-11-01' AND '2022-11-30'
#                        OR HISTORY.END_DATE BETWEEN '2022-11-01' AND '2022-11-30')
# ORDER BY FEE DESC, CAR.CAR_TYPE DESC;



# SLECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY


SELECT CAR.CAR_ID, CAR.CAR_TYPE, FLOOR((CAR.DAILY_FEE*30)*(1-(PLAN.DISCOUNT_RATE/100))) FEE FROM CAR_RENTAL_COMPANY_CAR CAR
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
ON CAR.CAR_TYPE=PLAN.CAR_TYPE 
AND CAR.CAR_TYPE IN ('세단','SUV') 
AND PLAN.DURATION_TYPE LIKE '30일 이상'
AND (CAR.DAILY_FEE*30)*(1-(PLAN.DISCOUNT_RATE/100)) BETWEEN 500000 AND 2000000
WHERE CAR.CAR_ID NOT IN (
    SELECT DISTINCT(HISTORY.CAR_ID)  
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
    WHERE HISTORY.START_DATE <= '2022-11-30' 
    AND HISTORY.END_DATE >= '2022-11-01'
)
ORDER BY FEE DESC, CAR.CAR_TYPE DESC;




# 자동차 종류가 '세단' 또는 'SUV' 인 자동차 
# 2022년 11월 1일 - 2022년 11월 30일 대여 가능
 # 대여 금액이 50만원 이상 200만원 미만