-- 코드를 입력하세요
WITH HISTORY AS(
    SELECT history_id, DATEDIFF(end_date,start_date)+1 AS day, daily_fee   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
    LEFT JOIN CAR_RENTAL_COMPANY_CAR AS CAR ON CAR.CAR_ID=HISTORY.CAR_ID
    WHERE CAR.CAR_TYPE='트럭'
), DISCOUNT_TRUCK AS(
    SELECT SUBSTRING_INDEX(DURATION_TYPE,'일',1) AS DAY,DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE='트럭'
)



SELECT HISTORY_ID, FLOOR(CASE
                    WHEN day>=90 THEN (daily_fee*day)* (SELECT 100-DISCOUNT_RATE FROM DISCOUNT_TRUCK WHERE DAY=90)/100
                    WHEN day>=30 THEN (daily_fee*day)* (SELECT 100-DISCOUNT_RATE FROM DISCOUNT_TRUCK WHERE DAY=30)/100
                    WHEN day>=7 THEN (daily_fee*day)* (SELECT 100-DISCOUNT_RATE FROM DISCOUNT_TRUCK WHERE DAY=7)/100
                    ELSE daily_fee*day
                    END
) AS FEE
FROM HISTORY
ORDER BY FEE DESC, HISTORY_ID DESC;