WITH JULY_FLAVOR as (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY
    GROUP BY FLAVOR
)

SELECT FIRST_HALF.FLAVOR AS FLAVOR FROM FIRST_HALF
INNER JOIN JULY_FLAVOR ON JULY_FLAVOR.FLAVOR=FIRST_HALF.FLAVOR
ORDER BY JULY_FLAVOR.TOTAL_ORDER+FIRST_HALF.TOTAL_ORDER DESC
LIMIT 3;



