-- 코드를 입력하세요
SELECT half.FLAVOR FROM FIRST_HALF half
LEFT JOIN ICECREAM_INFO info 
ON half.FLAVOR=info.FLAVOR
WHERE half.TOTAL_ORDER >3000 
AND info.INGREDIENT_TYPE LIKE 'fruit_based'
ORDER BY half.TOTAL_ORDER DESC;