-- 코드를 작성해주세요

# WITH MAX_FISH AS (
# SELECT FISH_INFO.FISH_TYPE, MAX(IFNULL(FISH_INFO.LENGTH,0))
# FROM FISH_INFO
# GROUP BY FISH_INFO.FISH_TYPE
# )

SELECT FISH_INFO.ID,FISH_NAME_INFO.FISH_NAME,FISH_INFO.LENGTH
FROM FISH_INFO
LEFT JOIN FISH_NAME_INFO ON FISH_NAME_INFO.FISH_TYPE=FISH_INFO.FISH_TYPE
WHERE (FISH_INFO.FISH_TYPE,FISH_INFO.LENGTH) IN (SELECT FISH_INFO.FISH_TYPE, MAX(IFNULL(FISH_INFO.LENGTH,0))
FROM FISH_INFO
GROUP BY FISH_INFO.FISH_TYPE)
ORDER BY ID ASC;
